In [1]:


from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
import pyautogui

In [2]:
# tinha um erro na planilha, o nome da caixa estava com um caractere especial, então eu fiz esse código para substituir o caractere especial pelo correto
# Ler o arquivo CSV completo
tabela = pd.read_csv('lis_teste.csv', sep='\t', header=None)

# Iterar sobre todas as células da tabela e substituir o texto
for i in range(tabela.shape[0]):
    for j in range(tabela.shape[1]):
        if isinstance(tabela.iloc[i, j], str):
            tabela.iloc[i, j] = tabela.iloc[i, j].replace('Caixa EconÃ´mica Federal', 'Caixa Economica Federal')


# Excluir o índice 0
tabela = tabela.drop(0)

# Mostrar a tabela somente com o cpf e a matricula
tabela = tabela[[0, 7]]
tabela.columns = ['cpf', 'matricula']

# Ajustar o índice para refletir a remoção da linha
tabela = tabela.reset_index(drop=True)

# Exibir a tabela
display(tabela)

            cpf  matricula
0   22921265249  415669820
1   32335733249  474278166
2   87483920300  259213217
3   77551460225  474147363
4   41347528253  474187349
..          ...        ...
94  22763473415  283322969
95  95441085487  283432411
96   1021361496  474800970
97  54027519434  283314591
98  53979702472  474965490

[99 rows x 2 columns]